### ISSUE TITLE
(and, or, not) are colored blue, when written at the start, middle or end of a word

### ISSUE THREAD

**Issue by duianto** [ralesi/ahk-mode#18]
#### Description :octocat:

"and", "or", and "not" are colored blue, when they are written at the start, middle or end of a word.
#### Reproduction guide :beetle:
- Start Emacs
- Open an .ahk file or create a new one
- Type: `android_storage_knot`

_Observed behaviour:_ :eyes: :broken_heart:

![emacs_2016-10-08_19-25-34](https://cloud.githubusercontent.com/assets/13420573/19214844/7d35c3ae-8d8d-11e6-81dd-f5da4c93e7ec.png)

_Expected behaviour:_ :heart: :smile:
"and", "or", and "not" should keep the default text color when there isn't whitespace before and after them.

They should however keep the blue color when there is whitespace before and after, like it currently does, as shown in the screenshot above.
#### System Info :computer:
- OS: windows-nt
- Emacs: 25.1.1
- Spacemacs: 0.200.0
- Spacemacs branch: develop (rev. 405e90d)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:

``` elisp
(autohotkey emacs-lisp git helm)
```

Theme: 
spacemacs-dark (the default spacemacs theme)
#### Notes:

In the xahk-mode package, "and", "or", and "not" doesn't change color in words.

But commenting doesn't work very well there, it uses `/* */` style comments, but there's problems when one tries to toggle off the comments, sometimes it shows the message: `Can’t find the comment end`, and other times it adds another set of comments: `/* /\* test *\/ */`.

So i prefer this ahk-mode package, since the `;` comments can be toggled on and off without any issues.

**Comment by duianto** [comment]
"return" also gets highlighted when it's part of a word:

![return_highlighted_in_word](https://cloud.githubusercontent.com/assets/13420573/20627471/89bd15c4-b320-11e6-893b-8d45807f61f1.png)

**Comment by punassuming** [comment]
I will look into it

**Comment by humanfactors** [comment]
Any progress, this is still an issue for keywords like Force etc
