### ISSUE TITLE
License of the package

### ISSUE THREAD

**Issue by matsl** [ralesi/ahk-mode#20]
Hi,

Could not find any other contact info so opening an issue for this license request.

In a thread in the emacs-devel maillist, the licensing situation for emacs packages provided through Emacs package archives has been under focus. I have volunteered to contact the authors of packages that have a license that is incompatible with Emacs, which is now under GPL-3+.

See https://lists.gnu.org/archive/html/emacs-devel/2017-07/msg01069.html                                                                                                     

So I wonder if you could consider to change the license of your package to GPL-3+?

**Comment by tarsius** [comment]
This can be closed now. The updated terms can be seen at #28.

(Hey @matsl. :wink: )
