### ISSUE TITLE
Commented functions, labels, and keybinds show up in imenu

### ISSUE THREAD

**Issue by blaenk** [ralesi/ahk-mode#23]
I can't figure out why this is happening. By default imenu ignores comments assuming the syntax table is correctly defined.

**Comment by duianto** [comment]
This issue seems to have been fixed by this PR:

fix imenu #27 

* fix: commented functions, labels, and keybinds show up in imenu
* fix: if (foo = bar) \n { is also function in old version
* add Hotstrings
* comments beginning with `; imenu` can be seen in imenu
