### ISSUE TITLE
ahk-run-script: Symbol’s function definition is void: w32-shell-execute

### ISSUE THREAD

**Issue by stardiviner** [ralesi/ahk-mode#24]
I'm running command `ahk-run-script` from Arch Linux on ahk script file.
I installed package `ironahk-git`  https://github.com/Paris/IronAHK
Error: RT

**Comment by punassuming** [comment]
I haven't tried ironahk on Arch yet.  Is it still actively maintained?

**Comment by stardiviner** [comment]
Hmm, unlocky, I checked the AUR repository date, it's not maintained for a really lone time. Sorry for disturb.
I'm gonna close this issue anyway. And thanks, @ralesi
