### ISSUE TITLE
install failure

### ISSUE THREAD

**Issue by jack99999** [ralesi/ahk-mode#4]
hi
i tried installing and got:
Install package `ahk-mode-20150409.1012'? (y or n) y
Contacting host: melpa.milkbox.net:80
Making version-control local to ahk-mode-autoloads.el while let-bound!
Generating autoloads for ahk-mode.el...
forward-sexp: Scan error: "Unbalanced parentheses", 3648, 33041
When done with a buffer, type M-x server-edit
Error during redisplay: (jit-lock-function 3278) signaled (scan-error "Unbalanced parentheses" 3614 33007)
preceding-sexp: End of file during parsing

i downloaded the zip and had a look.... i think the problem is here:
;;; Requirements

(eval-when-compile
  (require 'font-lock)
  (require 'cl)
  (require 'thingatpt )
  (require 'rx)

cheers

jack

**Comment by punassuming** [comment]
thanks for letting me know.  Issue should be addressed now.

**Comment by jack99999** [comment]
yes, that's got it.

thanks

jack
