### ISSUE TITLE
Check if auto-complete-mode is installed

### ISSUE THREAD

**Issue by bk322** [ralesi/ahk-mode#8]
Hi,

Currently auto-complete-mode is a requirement:

```
(eval-after-load "auto-complete-mode"
  (progn
    (require 'auto-complete-config) 
    (add-to-list 'ac-modes 'ahk-mode)))
```

I'm on Emacs 24.3 and I don't have auto-complete-mode installed. Could you please check if it is installed first:

```
(featurep 'auto-complete-mode
          (eval-after-load "auto-complete-mode"
            (progn
              (require 'auto-complete-config) 
              (add-to-list 'ac-modes 'ahk-mode))))
```

**Comment by punassuming** [comment]
@bk322 eval-after-load should work without checking featurep.  I forgot to quote the progn though.  Will submit a fix tonight.

**Comment by punassuming** [comment]
@bk322,  I submitted a commit a while back, are you still having the same issue?
