### ISSUE TITLE
File mode specification error: (wrong-type-argument arrayp nil)

### ISSUE THREAD

**Issue by highend** [ralesi/ahk-mode#9]
Hi,

I get this error when I open an .ahk file.

Windows Server 2012 R2 U1, german
Spacemacs 0.103.6
Emacs 24.5 (x64)

**Comment by punassuming** [comment]
@highend  ,  can you show me the backtrace for this error so I can find out what caused it?

**Comment by highend** [comment]
@ralesi 
Sure! I hope you can fix it...

`Debugger entered--Lisp error: (wrong-type-argument arrayp nil)
  replace-regexp-in-string("\\\\" "/" nil)
  byte-code("\302\303\304\"!\305\306\307\310\311  \312\"\211A@\262#!)\207" [ahk-registry reg-data shell-command-to-string format "reg query \"%s\"" file-name-directory replace-regexp-in-string "\\\\" "/" split-string "\\\""] 7)
  (defvar ahk-path (byte-code "\302\303\304\"!\305\306\307\310\311    \312\"\211A@\262#!)\207" [ahk-registry reg-data shell-command-to-string format "reg query \"%s\"" file-name-directory replace-regexp-in-string "\\\\" "/" split-string "\\\""] 7) ("d:/Tools/Emacs/config/.emacs.d/elpa/ahk-mode-20150410.857/ahk-mode.elc" . 2200))
  ahk-mode()
  set-auto-mode-0(ahk-mode nil)
  set-auto-mode()
  normal-mode(t)
  after-find-file(nil t)
  find-file-noselect-1(#<buffer test.ahk> "d:/Temp/test.ahk" nil nil "d:/Temp/test.ahk" (2533274790451300 3705691005))
  find-file-noselect("d:/Temp/test.ahk" nil nil nil)
  find-file("d:/Temp/test.ahk")
  mapc(find-file ("d:/Temp/test.ahk"))
  helm-find-many-files("d:/Temp/test.ahk")
  helm-execute-selection-action-1()
  helm-execute-selection-action()
  #[0 "\311\211\211\211\305\206\n`

**Comment by punassuming** [comment]
@highend Latest commit should address the issue.  I think you were missing the registry keys for autohotkey.

**Comment by punassuming** [comment]
@highend, Is this fixed now?
